### ISSUE TITLE
Backend: New feature to GET branding details like logo,app name , theme

### ISSUE THREAD

**Issue by dileep-gadiraju** [project-anuvaad/Project-Saral#58]
Backend: New feature to GET,POST branding details like logo, app name, theme

- Logo image should be BASE64 encoded string
- App name should be text
- Theme colour should be switched.

The front end would use this API response based on the state of the school to switch logo, App name and Theme.

The response should look like this:

{
  "logoImage": "",
  "appName": "Saral OCP Application",
  "theme": "<colour>"
}

**Comment by dileep-gadiraju** [comment]
@apurvabisht97 , close this after validating all the apis

**Comment by apurvabisht97** [comment]
These APIs is created successfully .
