### ISSUE TITLE
Frontend: Mark Absent Present UI Integration

### ISSUE THREAD

**Issue by dileep-gadiraju** [project-anuvaad/Project-Saral#63]
Frontend: Mark Absent Present UI Integration. Refer Swagger documentation after https://github.com/project-anuvaad/Project-Saral/issues/62 developed and integrate with frontend.

**Comment by dileep-gadiraju** [comment]
Absent/present functionality not working. it shows possible unhandled Promise rejection error.

**Comment by dileep-gadiraju** [comment]
Absent/Present functionality is not working currently.

**Comment by dileep-gadiraju** [comment]
Marks Absent/Present is failing with the below error:

Possible Unhandled Promise Rejection (id: 1):
                             │ TypeError: undefined is not an object (evaluating '**scanedData.data.length**')
                             │ _callee$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:147268:46
                             │ tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:23401:23
                             │ invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:23571:32
                             │ tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:23401:23
                             │ invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:23473:30
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:23483:21
                             │ tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:28076:16
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:28177:27
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:28692:26
                             │ _callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:28588:17
                             │ _callImmediatesPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:28627:17
                             │ callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:28837:33
                             │ __callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:3054:35
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:2832:34
                             │ __guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:3037:15
                             │ flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true:2831:21
                             │ flushedQueue@[native code]
                             └ invokeCallbackAndReturnFlushedQueue@[native code]

**Comment by dileep-gadiraju** [comment]
@apurvabisht97 , please close this after ur full fledged testing.

**Comment by apurvabisht97** [comment]
integration of absent/present from frontend is working correctly .
Case1:-  When we are marking any student as absent then we are not able to scan marks for that particular student .
Case2:-  When if students marks is saved in db and local storage and we will try to mark it as absent then it will give validation error .
