### ISSUE TITLE
axios showing btoa error while calling api in between 0.21 version and 0.19

### ISSUE THREAD

**Issue by arman-tdev** [project-anuvaad/Project-Saral#71]
Save All Scans failing with below error:
ReactNativeJS ▶︎ '>>>>>>>>>>Error here', { [ReferenceError: Can't find variable: btoa]
                             │ line: 111146,
                             │ column: 55,
                             └ sourceURL: 'http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.saralapp&modulesOnly=false&runModule=true' }

**Comment by dileep-gadiraju** [comment]
https://stackoverflow.com/questions/42829838/react-native-atob-btoa-not-working-without-remote-js-debugging

**Comment by dileep-gadiraju** [comment]
Fixed as per suggestion given in above link , so close the issue.
