### ISSUE TITLE
Navigation Issue: Between scan screen and scan summary screen there is no way to navigate

### ISSUE THREAD

**Issue by dileep-gadiraju** [project-anuvaad/Project-Saral#72]
Navigation Issue: Between the scan screen and scan summary screen there is no way to navigate.
Suggestion: Add a button "Scan Summary" on scan screen to go back to summary screen and Save All scans to backend.

**Comment by dileep-gadiraju** [comment]
@navin9584 , verify this and close as nav is fixed now.

**Comment by navin9584** [comment]
this issue is fixed
