### ISSUE TITLE
Feature: Capture Training Data in the response

### ISSUE THREAD

**Issue by dileep-gadiraju** [project-anuvaad/Project-Saral#73]
Feature: Capture Training Data in the response based on login storeTrainingData flag.
Default value of this flag should be false.

**Comment by dileep-gadiraju** [comment]
Saral SDK code changed to capture the roi Mat image and encode (Base64) and include it in SDK response as result.roiImage element.

**Comment by dileep-gadiraju** [comment]
Backend changes as per design implemented by @apurvabisht97. So assigning to Arman to complete frontend changes and testing.

**Comment by apurvabisht97** [comment]
For Training Data in marks collection  we have added two more fields  that is studentIdTrainingData and trainingData in 
marksInfo.

Example:-  

{
    "studentIdTrainingData": [],
    "studentAvailability": true,
    "createdOn": "1634884011708",
    "section": "B",
    "studentId": "30000001",
    "securedMarks": 0,
    "totalMarks": 0,
    "marksInfo": [{
        "trainingData": [],
        "questionId": "QUESTION1",
        "obtainedMarks": "55"
    }, {
        "trainingData": [],
        "questionId": "QUESTION4",
        "obtainedMarks": "55"
    }],
    "schoolId": "3",
    "examDate": "05/10/2021",
    "subject": "Hindi",
    "classId": "4",
    "__v": 0
}

And in school API we have added one field to show that trainingData is available or not by default its false ... only for odisha I have marked as true .. So you can test it with odisha sheet .

**Comment by apurvabisht97** [comment]
training data requirement is done .

when school flag is true then we will get training data while saving marks .
when flag is false then we will not get training data while saving marks .
