### ISSUE TITLE
Marks Obtained Validation is not working as expected for odisha and up layouts

### ISSUE THREAD

**Issue by dileep-gadiraju** [project-anuvaad/Project-Saral#74]
Marks Obtained Validation is not working as expected for odisha and up layouts.

After scanning, override marks for each question as 1 and provide marks obtained as 20 or 34 as per layout , the validation is still failing. For 20 questions sheet , Marks obtained =20 the validation has to pass.
Check check this and fix the issue.

**Comment by apurvabisht97** [comment]
this issue was due to incorrect roi generation by python script . now it is fixed
